export default {
  1: {
    title: "Selecciona la opción correcta",
    desc: "¿Cómo definirías al objeto formal y material en el ámbito de la ciencia?",
    one: "El objeto material es aquello de lo que trata la disciplina en cuestión y el objeto formal es la perspectiva o problema que se plantea respecto del objeto material.",
    two: "El objeto material se refiere al material físico con el que se construye un objeto, como la madera en una silla o el metal en un automóvil. El objeto formal, por otro lado, es la forma o estructura que toma ese material.",
    three:
      "El objeto material se refiere al material físico con el que se construye un objeto, como la madera en una silla o el metal en un automóvil. El objeto formal, por otro lado, es simplemente una etiqueta que se le da a algo para clasificarlo. No tiene una función real o significado más profundo.",
    four: "El objeto material es solo un término elegante para referirse a cualquier cosa física que puedas tocar. Así que, básicamente, todo es un objeto material, y el objeto formal es la perspectiva o problema que se plantea respecto del objeto material.",
    true: 1,
  },
  2: {
    title: "Selecciona la opción correcta",
    desc: "Basado en la pregunta anterior, ¿Cuál podría definirse cómo objeto formal y material de la gestión de personal?",
    one: "El objeto formal de la gestión de personal se refiere a su ámbito de acción y propósito. En otras palabras, es la naturaleza o esencia de lo que la gestión de personal busca lograr. El objeto material de la gestión de personal se refiere a las tareas y funciones específicas que realiza el departamento de recursos humanos para cumplir con su objeto formal.",
    two: "El objeto material de la gestión de personal son las personas, infraestructura y recursos de la empresa. El objeto formal es el criterio de departamentalización.",
    three:
      "El objeto material de la gestión de personal se refiere a las tareas y funciones específicas que realiza el departamento de recursos humanos para cumplir con su objeto formal. El objeto formal es el criterio de departamentalización.",
    four: "El objeto formal de la gestión de personal se refiere a su ámbito de acción y propósito. En otras palabras, es la naturaleza o esencia de lo que la gestión de personal busca lograr. El objeto material de la gestión de personal son las personas, infraestructura y recursos de la empresa.",
    true: 1,
  },
  3: {
    title: "Seleccione la disciplina errónea",
    desc: "¿Cuál de las siguientes disciplinas no está incorporada en la gestión de personal?",
    one: "La medicina del trabajo.",
    two: "La ingeniería de sistemas.",
    three: "La informática.",
    four: "Ninguna de las anteriores.",
    true: 4,
  },
  4: {
    title: "Selecciona el condicionante",
    desc: "¿Cuál de los siguientes condicionantes no es solamente interno?",
    one: "Tamaño de la organización",
    two: "La cultura",
    three: "Criterio de departamentalización",
    four: "La alta gerencia",
    true: 2,
  },
  5: {
    title: "Selecciona el objetivo",
    desc: "¿Cuál de los siguientes objetivos busca contribuir al éxito de la empresa mediante la alineación con la estrategia global?",
    one: "Objetivos funcionales",
    two: "Objetivos personales",
    three: "Objetivos sociales",
    four: "Objetivos corporativos",
    true: 4,
  },
  6: {
    title: "Selecciona la razon",
    desc: "Selecciona una de las principales razones de la creciente importancia de la gestión del personal.",
    one: "La gestión del personal se ha vuelto más importante debido al auge de las empresas tecnológicas unicornio.",
    two: "En la era de las redes sociales, la gestión del personal se ha vuelto crucial debido a la creciente influencia de los memes.",
    three:
      "En los últimos años, el mundo ha experimentado cambios profundos debido a la globalización.",
    four: "Ninguna de las anteriores.",
    true: 3,
  },
  7: {
    title: "Selecciona la opción correcta",
    desc: "La conducta en las organizaciones se caracteriza por varios aspectos fundamentales, ¿Cuál de los siguientes no es uno de ellos?",
    one: "Capacidad limitada de dar respuesta.",
    two: "Diversidad de necesidades",
    three: "Socialidad",
    four: "Todas las anteriores son aspectos fundamentales.",
    true: 4,
  },
  8: {
    title: "Selecciona la opción correcta",
    desc: "Según la teoría estructuralista, ¿Cómo se considera a la naturaleza humana en el contexto organizacional?",
    one: "Se basa en la idea de que las personas están motivadas principalmente por recompensas salariales y materiales.",
    two: "Destaca la importancia de las recompensas sociales y simbólicas como motivadores para el trabajo en grupo. Reconoce la necesidad humana de pertenencia y aceptación social.",
    three:
      "Considera al individuo como parte integral de las organizaciones, desempeñando roles diferentes en cada una de ellas y dependiendo de ellas para satisfacer sus necesidades.",
    four: "Enfatiza la capacidad del individuo para procesar información y tomar decisiones de manera constante en su entorno laboral.",
    true: 3,
  },
  9: {
    title: "Selecciona la opción correcta",
    desc: "El concepto de hombre complejo se basa en varias razones fundamentales, una de ellas es el Dominio del mundo exterior, selecciona su definición.",
    one: "Los seres humanos tienen múltiples motivaciones que pueden cambiar con el tiempo y según la situación. Estas motivaciones pueden ser complejas y están interrelacionadas entre sí.",
    two: "Los individuos buscan emplear sus habilidades para resolver conflictos y superar problemas en su entorno organizativo.",
    three:
      "Las personas responden de manera diferente a las estrategias de dirección debido a sus motivaciones, habilidades y la naturaleza de su trabajo. No existe una estrategia de dirección universalmente efectiva.",
    four: "Las motivaciones de una persona pueden variar según el tipo de organización en la que se encuentre. Una persona puede satisfacer ciertas necesidades en una organización formal y otras en organizaciones informales o sindicatos.",
    true: 2,
  },
  10: {
    title: "Selecciona la opción correcta",
    desc: "¿Cuál de las siguientes premisas no explica la conducta humana?",
    one: "La conducta está influenciada por estímulos externos o internos. Tanto la genética como el ambiente tienen un papel decisivo en el comportamiento humano.",
    two: "La conducta está motivada, es decir, tiene un propósito. No es aleatoria, sino que siempre se dirige hacia un objetivo.",
    three:
      "La conducta está orientada a objetivos. En todo comportamiento, existe una necesidad, impulso o deseo que actúa como motivación.",
    four: "Todas son correctas.",
    true: 4,
  },
  11: {
    title: "Selecciona el enunciado correcto",
    desc: "¿Cuál de los siguientes enunciados corresponde al ciclo motivacional?",
    one: "El mismo comienza con la aparición de una necesidad, una fuerza persistente que impulsa el comportamiento. Esta necesidad rompe el equilibrio del organismo y genera un estado de tensión, insatisfacción y desequilibrio. Para aliviar esta tensión, el individuo lleva a cabo acciones que buscan satisfacer la necesidad. Si estas acciones son efectivas, la necesidad se satisface y la tensión se libera.",
    two: "Ofrece una perspectiva interesante sobre la relación entre el dinero y el desempeño en el trabajo. Aunque el dinero puede ser un motivador poderoso, su efectividad puede verse comprometida por diversos factores en el entorno laboral.",
    three:
      "Se centra en dos categorías principales que afectan la satisfacción y la insatisfacción en el trabajo: los factores higiénicos y los factores motivacionales.",
    four: "Reconoce que no hay una única manera de motivar a las personas y que la motivación puede variar según la situación individual.",
    true: 1,
  },
  12: {
    title: "Selecciona la opción correcta",
    desc: "¿Cuál de las siguientes premisas no causa frustración en el entorno laboral?",
    one: "Demasiada carga de trabajo: Si te encuentras trabajando como una máquina y asumiendo todas las responsabilidades, es probable que la frustración esté a la vuelta de la esquina. La sobrecarga de trabajo puede agotar a los empleados y afectar su bienestar.",
    two: "Falta de control o autonomía: Cuando los empleados sienten que no tienen control sobre su trabajo o no pueden tomar decisiones importantes, pueden experimentar frustración. La autonomía es esencial para la satisfacción laboral.",
    three:
      "Falta de reconocimiento y aprecio: La falta de reconocimiento por el esfuerzo y los logros puede generar sentimientos de frustración. Los empleados quieren sentir que su trabajo es valorado y apreciado.",
    four: "El efecto del café descafeinado: Según esta teoría, la falta de cafeína en el café descafeinado está directamente relacionada con la frustración en el trabajo. Los empleados que beben café descafeinado tienden a tener más problemas con las fotocopiadoras y las contraseñas olvidadas.",
    true: 4,
  },
  13: {
    title: "Selecciona la opción errónea",
    desc: "El estilo de liderazgo de Iacocca se centraba en varios principios clave, ¿Cuál no es uno de ellos?",
    one: "Creación de una agenda para el cambio: Que incluya una visión de lo que puede y debe ser, una visión que tenga en cuenta los intereses legítimos a largo plazo de las partes implicadas, que incluya una estrategia para alcanzar esa visión, una estrategia que tenga en cuenta todas las fuerzas organizativas y del entorno.",
    two: "Creación de una sólida red de implantación: Que incluye relaciones de apoyo con las principales fuentes de poder necesarias para aplicar la estrategia, relaciones lo suficientemente sólidas como para suscitar la cooperación, la conformidad y (cuando sea necesario) el trabajo en equipo, que incluya un núcleo de personas altamente motivadas Un núcleo comprometido a hacer realidad la visión.",
    three:
      "El principio de la “reunión estratégica”: Según esta teoría, Iacocca creía en la importancia de las reuniones estratégicas con un enfoque específico. Cada semana, convocaba a su equipo para analizar detenidamente un solo aspecto crítico del negocio. En lugar de abordar múltiples temas, se centraban en uno solo, como la mejora de la calidad del producto o la expansión a nuevos mercados. Iacocca sostenía que esta concentración estratégica permitía tomar decisiones más informadas y efectivas.",
    four: "Todos son principios claves.",
    true: 3,
  },
  14: {
    title: "Selecciona el que no es un estilo de liderazgo",
    desc: "¿Cuál de los siguientes estilos no es un estilo de liderazgo?",
    one: "Liderazgo Transaccional",
    two: "Liderazgo Laissez-Faire",
    three: "Liderazgo de Servicio.",
    four: "Liderazgo Sans enthousiasme.",
    true: 4,
  },
  15: {
    title: "Selecciona la opción correcta",
    desc: "¿Qué es un dato?",
    one: "Es la representación de un registro objetivo de un evento o suceso específico.",
    two: "Conjunto de saberes que han sido procesados y que tienen un significado específico.",
    three:
      "Es el proceso mediante el cual la información se transmite de un emisor a uno o más receptores.",
    four: "Es un síntoma, es decir, una propiedad observable o evento que se considera la manifestación de una propiedad o evento observable, es dificil de diferenciarlo de un índice y es netamente matemático.",
    true: 1,
  },
  16: {
    title: "Selecciona la opción correcta",
    desc: "¿Cuál de las siguientes opciones es un tipo de barrera en la comunicación?",
    one: "Barreras personales: Estas barreras surgen de las limitaciones individuales, emociones y valores de cada persona. Ejemplos comunes incluyen malos hábitos de escucha, emociones intensas, motivaciones personales y sentimientos que pueden interferir con la comunicación efectiva.",
    two: "Barreras físicas: Se refieren a las interferencias en el entorno físico donde tiene lugar la comunicación. Esto puede incluir distracciones visuales o auditivas, como ruidos fuertes, dispositivos electrónicos que interfieren, distancia física entre los interlocutores o cualquier otro elemento del entorno que dificulte la transmisión o recepción del mensaje.",
    three:
      "Barreras semánticas: Estas barreras se relacionan con las limitaciones o distorsiones en el significado de los símbolos utilizados en la comunicación. Palabras, gestos, señales u otros símbolos pueden interpretarse de manera diferente por las partes involucradas, lo que puede llevar a malentendidos o distorsiones en el mensaje.",
    four: "Todas las anteriores.",
    true: 4,
  },
  17: {
    title: "Selecciona la opción correcta",
    desc: "Además de estas barreras, la comunicación también puede sufrir problemas adicionales, ¿Cuál no lo es?",
    one: "Omisiones: Cuando elementos importantes del mensaje son omitidos o cortados, ya sea por la fuente o el destinatario, lo que resulta en una comunicación incompleta o descontextualizada.",
    two: "Distorsiones: Cuando el mensaje experimenta cambios o alteraciones que afectan su contenido y significado original, lo que puede conducir a malentendidos o interpretaciones erróneas.",
    three:
      "El dilema de la jerga corporativa: A veces, la comunicación se ve afectada por el uso excesivo de jerga o términos técnicos específicos de una industria o empresa. Cuando los empleados se sumergen en un lenguaje especializado, corren el riesgo de alienar a quienes no están familiarizados con esos términos. Esto puede dificultar la comprensión y generar malentendidos.",
    four: "Sobrecarga: Ocurre cuando la cantidad de información es demasiado grande para que el destinatario la procese eficazmente, lo que puede resultar en la pérdida de parte del mensaje o en una comprensión distorsionada debido a la incapacidad para manejar la carga informativa.",
    true: 3,
  },
  18: {
    title: "Selecciona la opción que no pertenece",
    desc: "¿Cuál de los siguientes medios no pertenece a un sistema de comunicación descendente?",
    one: "Programas de sugerencias.",
    two: "Folletos.",
    three: "Mensajes grabados.",
    four: "Reuniones informativas.",
    true: 1,
  },
  19: {
    title: "Selecciona la opción que no esta comprendida",
    desc: "¿Cuál de los siguientes elementos no está comprendido en la comunicación no verbal?",
    one: "Tono de la voz.",
    two: "Gestos.",
    three: "Vestimenta.",
    four: "Todos los anteriores están comprendidos en la comunicación no verbal.",
    true: 4,
  },
  20: {
    title: "Selecciona el consejo",
    desc: "¿Cuál de las siguientes opciones es un consejo sobre el lenguaje corporal con las manos?",
    one: "Deben tener movimientos libres y no tapar el rostro de la persona con la que se está interactuando para que se sienta cómoda.",
    two: "Deben permanecer lo más relajadas posibles y de ser posible ocultas a la vista de la persona con la que interactuamos.",
    three:
      "Deben permanecer inquietas con movimientos frenéticos de modo que el receptor se sienta intimidado por nuestra presencia.",
    four: "Deben permanecer lo más relajadas posibles, haciendo gestos de calma en todo momento de ser posible.",
    true: 1,
  },
};
