export default {
  1: {
    title: "Este es el título de la primera pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 2,
  },
  2: {
    title: "Este es el título de la segunda pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 4,
  },
  3: {
    title: "Este es el título de la tercera pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 1,
  },
  4: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 3,
  },
  5: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 1,
  },
  6: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 2,
  },
  7: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 4,
  },
  8: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 4,
  },
  9: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 3,
  },
  10: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 1,
  },
  11: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 2,
  },
  12: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 4,
  },
  13: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 1,
  },
  14: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 3,
  },
  15: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 1,
  },
  16: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 2,
  },
  17: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 4,
  },
  18: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 4,
  },
  19: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 3,
  },
  20: {
    title: "Este es el títulos de la pregunta",
    desc: "Esta es la descripción de la pregunta",
    one: "Primera respuesta posible",
    two: "Segunda respuesta posible",
    three: "Tercera respuesta posible",
    four: "Cuarta respuesta posible",
    true: 1,
  },
};
